/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package access.restriction.vscode;

public class App {

    public static void main(String[] args) {
        com.sun.management.HotSpotDiagnosticMXBean hotspotMBean;
    }
}
